export const STRING_BUTTON: 'a[href*="/recursion"]' = 'a[href*="/recursion"]'
export const FIBONACCI_BUTTON: 'a[href*="/fibonacci"]' = 'a[href*="/fibonacci"]'
export const SORTING_BUTTON: 'a[href*="/sorting"]' = 'a[href*="/sorting"]'
export const STACK_BUTTON: 'a[href*="/stack"]' = 'a[href*="/stack"]'
export const QUEUE_BUTTON: 'a[href*="/queue"]' = 'a[href*="/queue"]'
export const LIST_BUTTON: 'a[href*="/list"]' = 'a[href*="/list"]'
export const BUTTON: "button" = "button"
export const INPUT: 'input' = 'input'
export const CIRCLE: '[data-testid=circleWrapper]' = '[data-testid=circleWrapper]'
export const CIRCLE_HEAD: '[data-testid=head]' = '[data-testid=head]'
export const CIRCLE_TAIL: '[data-testid=tail]' = '[data-testid=tail]'
export const COLOR_DEFAULT: '4px solid rgb(0, 50, 255)' = '4px solid rgb(0, 50, 255)'
export const COLOR_CHANGING: '4px solid rgb(210, 82, 225)' = '4px solid rgb(210, 82, 225)'
export const COLOR_MODIFIED: '4px solid rgb(127, 224, 81)' = '4px solid rgb(127, 224, 81)'
